# Cổng chạy ứng dụng
server.port=8088

# Cấu hình Database đọc từ Biến môi trường (Environment Variables)
# Nếu không có biến DB_URL trên Cloud, nó sẽ tự lùi về dùng localhost của máy bạn
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/microboard}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

# Tự động cập nhật bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true